var css = ".ajmtoaster,\n.ajmtoaster__inner,\n.ajmtoaster__title,\n.ajmtoaster__message,\n.ajmtoaster__dismiss {\n  box-sizing: border-box;\n}\n\n.ajmtoaster {\n  position: fixed;\n  width: 325px;\n  top: 10px;\n  right: 10px;\n  z-index: 999999;\n}\n\n.ajmtoaster__inner {\n  min-height: 60px;\n\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n\n  font-size: 16px;\n  font-family: \"Roboto\", sans-serif;\n  font-weight: 100;\n\n  padding: 15px 26px 15px 15px;\n  border-radius: 3px;\n}\n\n.ajmtoaster__inner.--success {\n  background: var(--ajmt-success);\n}\n\n.ajmtoaster__inner.--failure {\n  background: var(--ajmt-failure);\n}\n\n.ajmtoaster__inner.--warning {\n  background: var(--ajmt-warning);\n}\n\n.ajmtoaster__inner.--info {\n  background: var(--ajmt-info);\n}\n\n.ajmtoaster__inner {\n  color: var(--ajmt-white);\n}\n\n.ajmtoaster__title,\n.ajmtoaster__message,\n.ajmtoaster__dismiss {\n  margin: 0;\n  padding: 0;\n}\n\n.ajmtoaster__title {\n  line-height: 1.1;\n  font-weight: 400;\n}\n\n.ajmtoaster__message {\n  line-height: 1.3;\n}\n\n.ajmtoaster__message {\n  max-width: 100%;\n  max-height: 100px;\n  overflow: auto;\n  margin-top: 0;\n\n  font-size: 80%;\n  word-break: break-word;\n}\n\n.ajmtoaster__message.with-message {\n  margin-top: 10px;\n  margin-right: 10px;\n}\n\n.ajmtoaster__dismiss {\n  box-sizing: border-box;\n  border: none;\n  color: rgba(255, 255, 255, 0.81);\n  line-height: 1;\n  margin: 0;\n  height: 100%;\n  display: block;\n  font-weight: 100;\n  border-radius: 0;\n  min-height: 0;\n  padding: 0;\n  font-family: sans-serif;\n  padding: 0 8px;\n  font-size: 16px;\n\n  position: absolute;\n  right: 0;\n  top: 50%;\n  transform: translateY(-50%);\n}\n\n.ajmtoaster__dismiss,\n.ajmtoaster__dismiss:hover {\n  transition: background-color 200ms ease-in-out;\n}\n\n.ajmtoaster__dismiss {\n  background-color: rgba(0, 0, 0, 0.08);\n}\n\n.ajmtoaster__dismiss:hover {\n  cursor: pointer;\n  background-color: rgba(255, 255, 255, 0.07);\n}\n\n.ajmtoaster__dismiss:active {\n  background-color: rgba(0, 0, 0, 0.08);\n}\n\n.ajmtoaster__dismiss:focus {\n  outline: 0;\n}\n";

var css$1 = "/* Animation 1: appear */\n.ajmtoaster.--animation-appear,\n.ajmtoaster.--animation-appear.--active {\n    transition: transform var(--ajmt-duration) var(--ajmt-easing) 0ms,\n    opacity var(--ajmt-duration) var(--ajmt-easing) 50ms;\n}\n.ajmtoaster.--animation-appear {\n  opacity: 0;\n  transform: scale(1.1);\n}\n.ajmtoaster.--animation-appear.--active {\n  opacity: 1;\n  transform: scale(1);\n}\n";

var css$2 = ".ajmtoaster,\n.ajmtoaster.theme-default {\n  --ajmt-white: #fff;\n  --ajmt-success: #41d888;\n  --ajmt-failure: #f94416;\n  --ajmt-info: #0387d7;\n  --ajmt-warning: #ffbd02;\n  --ajmt-duration: 300ms;\n  --ajmt-easing: ease-in-out;\n}\n";

const themes = {
  animations: css$1,
  baseCss: css,
  default: css$2 + css
};

export default themes;
export { css$1 as animations, css as baseCss, css$2 as themeDefault };
//# sourceMappingURL=themes.js.map
